Update vault paths (#5)
This updates the vault paths in scripts as well as adds a useful error
code and message

diff --git a/1.X/scripts/set-vault-token b/1.X/scripts/set-vault-token
--- a/1.X/scripts/set-vault-token
+++ b/1.X/scripts/set-vault-token
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 # shellcheck shell=bash
-set -e
 set -o pipefail
 
 approle_authenticate () {
@@ -12,9 +11,8 @@ approle_authenticate () {
     > $HOME/.vault-token
 }
 
-if [ -e /bin/vault ]; then
-  #if [[ "$VAULT_ADDR" && "$VAULT_AUTH_GITHUB_TOKEN" ]]; then
-  if [[ "$VAULT_ADDR" ]]; then
+if [ -e "$(which vault)" ]; then
+  if [[ "$VAULT_ADDR" && "$VAULT_PAYLOAD" ]]; then
     # are we already authenticated?
     TOKEN_LOOKUP=$(vault token-lookup -format=json 2>/dev/null)
 
@@ -25,5 +23,11 @@ if [ -e /bin/vault ]; then
       # authenticate
       approle_authenticate
     fi
+  else
+    echo "Missing VAULT_ADDR or VAULT_PAYLOAD"
+    exit 1
   fi
+else
+  echo "can not find vault"
+  exit 1    
 fi
